'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------
Namespace AspNetWebFormsDataFederation

    Public Partial Class [Default]

        ''' <summary>
        ''' ASPxDashboard1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxDashboard1 As Global.DevExpress.DashboardWeb.ASPxDashboard
    End Class
End Namespace
