'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace AspNetWebFormsDataFederation


	Partial Public Class RootMaster

		''' <summary>
		''' Body control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Body As Global.System.Web.UI.HtmlControls.HtmlGenericControl

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' ASPxSplitter1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxSplitter1 As Global.DevExpress.Web.ASPxSplitter

		''' <summary>
		''' SplitterContentControl1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected SplitterContentControl1 As Global.DevExpress.Web.SplitterContentControl

		''' <summary>
		''' TitleLink control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected TitleLink As Global.System.Web.UI.HtmlControls.HtmlAnchor

		''' <summary>
		''' HeadLoginView control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected HeadLoginView As Global.System.Web.UI.WebControls.LoginView

		''' <summary>
		''' SplitterContentControl3 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected SplitterContentControl3 As Global.DevExpress.Web.SplitterContentControl

		''' <summary>
		''' Content control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Content As Global.System.Web.UI.WebControls.ContentPlaceHolder

		''' <summary>
		''' SplitterContentControl4 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected SplitterContentControl4 As Global.DevExpress.Web.SplitterContentControl

		''' <summary>
		''' ASPxLabel2 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxLabel2 As Global.DevExpress.Web.ASPxLabel
	End Class
End Namespace